// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhphegeqyjkzcphiynna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocGhlZ2VxeWpremNwaGl5bm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjIyMzQsImV4cCI6MjA3MjgzODIzNH0.ABIDvFgTgEjMvJU7yGVvCqFZiqn3XKDqPpVIzypH9j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});